# This is a dockerfile to create a container for holding custom incore keycloak theme files
FROM busybox

# set working directory
WORKDIR /app

# copy your incore theme files into the container
COPY keycloakThemes/incore-theme /app/keycloak_theme

