name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'release/*'

    tags:
      - '*'

  pull_request:
    branches:
      - main
      - develop
      - 'release/*'
      -
env:
  MAIN_REPO: IN-CORE/incore-ui

jobs:

  # ----------------------------------------------------------------------
  # NODE BUILD
  # ----------------------------------------------------------------------
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node:
          - "12"
          - "14"

    steps:
      # checkout source code
      - uses: actions/checkout@v3

      # setup node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # install dependencies
      - name: install dependencies
        run: npm install

      # compile UI
      - name: build
        run: npm run build
